d /var/lib/renogymon-archiver                     0755 renogymon-archiver renogymon-archiver -
d /var/lib/renogymon-archiver/staging             0755 renogymon-archiver renogymon-archiver -
d /var/lib/renogymon-archiver/.ssh                0700 renogymon-archiver renogymon-archiver -
f /var/lib/renogymon-archiver/.ssh/authorized_keys 0600 renogymon-archiver renogymon-archiver -
